### ISSUE TITLE
examples or more info

### ISSUE THREAD

**Issue by deserthero** [vincentbrison/dualcache#29]
hello, 
now i want to use doublecache.
i prepared all the needed gradle lines and now i want to instantiate the caching service object.

In your description this is the lines to do that:
```
cache = new Builder<>(CACHE_NAME, TEST_APP_VERSION, AbstractVehicule.class)
    .enableLog()
    .useReferenceInRam(RAM_MAX_SIZE, new SizeOfVehiculeForTesting()
new SizeOfVehiculeForTesting())
    .useSerializerInDisk(DISK_MAX_SIZE, true, new DualCacheTest.SerializerForTesting(), getContext())
    .build();
```

but what is the type of cache object ?
what is AbstractVehicule.class means, i try to get it's declaration to understand but i didn't found comments?
what should be the default or recommanded number for RAM_MAX_SIZE, DISK_MAX_SIZE
what is  new DualCacheTest.SerializerForTesting(), new SizeOfVehiculeForTesting()

I really don't understand how to use it and i didn't find any tutorials, examples, real codes help?
so please help?

**Comment by vincentbrison** [comment]
Hi,

You are looking for the `Builder.class` [documentation](https://github.com/vincentbrison/dualcache/blob/master/dualcache-library/src/main/java/com/vincentbrison/openlibraries/android/dualcache/Builder.java).

By the way,
`AbstractVehicule.class` can be anything. This is what you want to store in your cache. It could be a class `User.java`.
 For the RAM size and the Disk size, it represents the maximum size used in RAM and on Disk in bytes. So it depends what you want to store in your cache. If it is large array of bytes (for Bitmap for example), it would be something in MB. Ultimately, if you are using both RAM and Disk layer, you may want to have a larger Disk cache size than RAM cache size.
DualCacheTest.SerializerForTesting(), new SizeOfVehiculeForTesting() are class used for testing.

BR

**Comment by deserthero** [comment]
`AbstractVehicule.class can be anything. This is what you want to store in your cache. It could be a class User.java.`

Is that mean for every object type i want to store i need to create cache object ?

**Comment by vincentbrison** [comment]
It depends the way you want [to serialize your objets](https://github.com/vincentbrison/dualcache/blob/master/dualcache-serializerinterface/src/main/java/com/vincentbrison/openlibraries/android/dualcache/CacheSerializer.java). If you are opting for a Json serializer like the `dualcache-jsonserializer`, it can support polymorphism. This is whats is done in [testing classes](https://github.com/vincentbrison/dualcache/tree/master/dualcache-library/src/androidTest/java/com/vincentbrison/openlibraries/android/dualcache/lib/testobjects). 

You could even choose to store different class without polymorphism, using as top class of your cache the Object class and providing specific behavior in your `CacheSerializer` and `SizeOf` implementation, using `instanceof` to handle each different class you want to cache.
