### ISSUE TITLE
Any putSync method/callback?

### ISSUE THREAD

**Issue by Try4W** [vincentbrison/dualcache#30]
```
            dualCache.put(key, object);
            logger.debug("put_result: " + "key " + key + "/" + object);
            logger.debug("demo_get: " + "key " + key + "/" + dualCache.get(key));
```

Sometimes `dualCache.get(key)` returns `null`. Is there any callback or sync way to put object in cache?

**Comment by Try4W** [comment]
New details about this issue.

If cache size is over the limit, then I can get `dualCache.get(key)` right after `dualCache.put(key, object);`
But after a moment, dualCache.get(key) returns null.

p.s. I don't use ram cache

**Comment by vincentbrison** [comment]
Hi,

I will look into provide some way to get the status of caching after a `put`. But I do not get your second message, cache size has the limit you set, how it could be `over the limit` ?

**Comment by Try4W** [comment]
> I will look into provide some way to get the status of caching after a put. 

Thanks for it.

> how it could be `over the limit` ?

It's kind of situation when you trying to put data about 2MB when cache limit size is 1MB.

**Comment by vincentbrison** [comment]
Thats weird. If you put data larger than the cache size, it just wont be stored in the cache. Which way of serialization do you use on disk ? Or even better, can you provide a sample ?

**Comment by Try4W** [comment]
I will try to write test that represents this bug later.

**Comment by vincentbrison** [comment]
Will re-open with more info.
