### ISSUE TITLE
Any feature or api to remove expired cache?

### ISSUE THREAD

**Issue by coasterleung** [vincentbrison/dualcache#32]
for example, i would like to remove the cache content that is not modified for over a month, how can i implement this feature?

**Comment by vincentbrison** [comment]
Hi,
This subject was discussed in #20 . I prefer to not implement such specific feature in the cache, to keep the cache effective and simple. You can implement such behaviour using the [decorator pattern](https://en.wikipedia.org/wiki/Decorator_pattern) for example.
BR.
