### ISSUE TITLE
How to use this dualcahe library??

### ISSUE THREAD

**Issue by vidyajejurkar** [vincentbrison/dualcache#33]
Can anyone tell me how to use this dualcache?
can i use this with jsondata?

**Comment by vincentbrison** [comment]
Hi,

- The [README.md](https://github.com/vincentbrison/dualcache/blob/master/README.md) is a good starter point. 

- Then you can take a look at the [demo project](https://github.com/vincentbrison/dualcache/tree/master/dualcache-demoapp). 

- Finally, the cache is fully documented trough Javadoc, so you can learn more directly using using it.

BR.

**Comment by vidyajejurkar** [comment]
Hi vincentbrison,thanks for reply.
i m new in android just wantto do offlione storage using Cache.i m little bit confised dual cache is libarary of (DiskLru cache and Lrucache) so i have to just import it or something else?
need ur help
