### ISSUE TITLE
license & Proguard options

### ISSUE THREAD

**Issue by swabbass** [vincentbrison/dualcache#34]
Hey ,

Thanks for the very helpful lib ,

how can i include your license in my app for release 

and what is the configurations for proguard 

thanks in advance

**Comment by vincentbrison** [comment]
Hi,
Thanks for your feedback. You can use [this](https://github.com/vincentbrison/dualcache#license) as the license.
I do not support Progard for now, but I think this should works:
`-keep class com.vincentbrison.openlibraries.android.dualcache.** { *; }`

Please re open this issue you felt this configuration is not working.

**Comment by swabbass** [comment]
Hi,

Thank you for now 

:D
