### ISSUE TITLE
Add Progard configuration

### ISSUE THREAD

**Issue by vincentbrison** [vincentbrison/dualcache#35]

**Comment by OmarBizreh** [comment]
Soo... Where can we find pro guard rules?

**Comment by vincentbrison** [comment]
Hi,
For now you can use https://github.com/vincentbrison/dualcache/issues/34.
Proguard configuration will be part of the next release of DualCache.
BR.

**Comment by OmarBizreh** [comment]
Ok, great. Thanks for your help :)
