### ISSUE TITLE
Got error when i am trying to create jar file

### ISSUE THREAD

**Issue by vidyajejurkar** [vincentbrison/dualcache#36]
hi vincentbrison ,i am tring to generate library using gradle.i installed gradle independently i dont have android studio setup.but when i ma trying to create jar using gradlew.bat got errr Plugin is too old, please update to a more recent version, or set ANDROID_DAILY_
how can i solve it?

**Comment by vincentbrison** [comment]
Hi,
You do not need to create yourself the jar for this library. You should set up the library [using this guide](https://github.com/vincentbrison/dualcache#setup).
BR.

**Comment by vidyajejurkar** [comment]
ok vincentbrison but i am using eclipse so how can i use this library?

**Comment by vincentbrison** [comment]
Eclipse is not supported [to do Android development](http://android-developers.blogspot.fr/2015/06/an-update-on-eclipse-android-developer.html). You should use Android Studio.
