### ISSUE TITLE
It's possible to set a live time to the cache entries?¿

### ISSUE THREAD

**Issue by iagocanalejas** [vincentbrison/dualcache#41]

**Comment by vincentbrison** [comment]
Yes you can, but you should implement this yourself to keep the library small and testable.
So you could use custom entries with two fields, one for live time, and the other to store you data. Using the [decorator pattern](https://en.wikipedia.org/wiki/Decorator_pattern), you could set the live time on `put` function and test the live time on `get` function.
BR
