### ISSUE TITLE
What about closing?

### ISSUE THREAD

**Issue by gustavkarlsson** [vincentbrison/dualcache#46]
`DiskLruCache` implements `Closeable` which leads me to believe it should be properly closed when it's done.

I see no way of doing that in the `DualCache` interface. Shouldn't `DualCache` also implement `Closeable` to allow for closing the underlying `DiskLruCache`?

**Comment by vincentbrison** [comment]
It may be useful. In what case you would need to close the cache ? For releasing memory ?

**Comment by gustavkarlsson** [comment]
I don't know much about the internals of `DiskLruCache`, but you are essentially breaking the interface contract by never closing it.

In general, the presence of `Closeable` or `AutoCloseable` tells us that this class needs to be closed to clean up it's resources, whatever they may be. When working with a file system it usually includes things such as flushing streams, releasing file locks, deleting temp files and similar things.

In this specific case, it looks like it gets rid of some temp file (with a hard coded name). I'm pretty sure that opening a second `DiskLruCache` in the same directory without closing the first one will cause issues with this temp file.

**Comment by vincentbrison** [comment]
I doubt there is an issue with this specific case. Is there is any, feel free to open an issue with a reproductible case.

Since next version of this library will target streams, `Closeable` will probably be added at this time.

**Comment by gustavkarlsson** [comment]
Better safe than sorry? It's a pretty trivial implementation...

**Comment by vincentbrison** [comment]
I am open to PR 😉
