### ISSUE TITLE
Is it possible to serialize to byte array instead of String?

### ISSUE THREAD

**Issue by roastduck** [vincentbrison/dualcache#49]
Hi, I can use Java's built-in `ObjectOutputStream` to serialize my data into a byte array instead of using the heavy JSON. But there might be some byte illegal for String, e.g. '\0' in the middle of the string. Do I have to encode my byte array to something like base64 or can I store the byte array into String directly using charset ISO-8859-1 (8-bit)? Furthermore, I hope byte arrays can be supported directly in interface `CacheSerializer`.

**Comment by vincentbrison** [comment]
Hello,
`CacheSerializer` should rely on `byte` array instead of `String`. I will include this in the next major release.
